// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWL64DeGYM_3pi81bJ40WfVaeK0TA99zI',
    appId: '1:600368849351:web:3e8137cdd2d603b30839e2',
    messagingSenderId: '600368849351',
    projectId: 'karinderyago',
    authDomain: 'karinderyago.firebaseapp.com',
    storageBucket: 'karinderyago.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd-KYqoNHkwG-KJD43MnqqifUBobw67Fc',
    appId: '1:600368849351:android:b5d93c3228f710e50839e2',
    messagingSenderId: '600368849351',
    projectId: 'karinderyago',
    storageBucket: 'karinderyago.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEftNNM2q36QyEmUihx4j1-71lKr-S-hI',
    appId: '1:600368849351:ios:b39c4d40e7d1554e0839e2',
    messagingSenderId: '600368849351',
    projectId: 'karinderyago',
    storageBucket: 'karinderyago.appspot.com',
    iosClientId: '600368849351-4mkta6pu9j0l4juloujtscsbm05hv9k3.apps.googleusercontent.com',
    iosBundleId: 'com.example.karinderyaGo',
  );
}
